- hosts: undercloud
  name: Gather facts undercloud
  gather_facts: yes
  become: false
- hosts: overcloud
  name: Gather facts overcloud
  gather_facts: yes
- hosts: all
  name: Load global variables
  gather_facts: no
  tasks:
    - include_vars: global_vars.yaml
- hosts: overcloud
  name: Run update
  serial: 1
  gather_facts: no
  tasks:
    - include: update_steps_tasks.yaml
      with_sequence: start=0 end=5
      loop_control:
        loop_var: step
    - include: common_deploy_steps_tasks.yaml
      with_sequence: start=1 end=5
      loop_control:
        loop_var: step
